# Generated by Django 4.2.8 on 2025-04-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name_plural': 'Mensajes de contacto'},
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
