# Generated by Django 4.2.8 on 2025-04-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_custom',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
