# Generated by Django 4.2.8 on 2025-04-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_customer_id_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_custom',
        ),
        migrations.AddField(
            model_name='customer',
            name='id_cliente',
            field=models.IntegerField(default=0),
        ),
    ]
